### ISSUE TITLE
template for nbsphinx that hides the ipython prompt numbers

### ISSUE THREAD

**Issue by phaustin** [cliburn/sta-663-2017#1]
Quick question if you've got a minute: I'm moving towards notebooks + nbsphinx for my course notes next year, and really like your rendered html that omits the ipython prompt number and makes a separate code block for the cell output.  Is that a custom template you've developed, or an option for nbsphinx that I'm missing?  I see the conf.py and Makefile for
https://github.com/cliburn/cfar-data-workshop-2016
but it looks like you've moved to your own preprocessing step to build this year's course?

**Comment by cliburn** [comment]
The only thing I do that is not vanilla nbsphinx is the use of the [cloud theme](https://cloud-sptheme.readthedocs.io/en/latest/contents.html).

**Comment by phaustin** [comment]
took another look at the nbsphinx conf.py and it looks like changing the default prompt width
fro 8ex to:

nbsphinx_prompt_width = '0ex'

is one way to get the prompt to disappear.
